version: '2'
services:
  virtuoso-dev:
    image: tenforce/virtuoso
    container_name: ontowiki-devenv-virtuoso-dev
    environment:
      DBA_PASSWORD: owdev
      SPARQL_UPDATE: "true"
    volumes:
      - /data

  mysql-dev:
    image: mysql
    container_name: ontowiki-devenv-mysql-dev
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: php
      MYSQL_PASSWORD: owdev
      MYSQL_DATABASE: ontowiki-dev
    volumes:
      - /var/lib/mysql

  phpserver:
    build: ./docker/php
    image: ontowiki-devenv/phpserver
    container_name: ontowiki-devenv-phpserver
    volumes:
      - ./..:/var/www
    links:
      - virtuoso-dev
      - mysql-dev

  nginx:
    build: ./docker/nginx
    image: ontowiki-devenv/nginx2
    container_name: ontowiki-devenv-nginx
    volumes:
      - ./..:/var/www
    links:
      - phpserver
    ports:
      - "8080:80"
